apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-main
  namespace: monitoring
spec:
  mode: deployment
  config: |
   receivers:
     zipkin:
       endpoint: 0.0.0.0:9411
   exporters:
     otlp:
       endpoint: tempo.monitoring:4317
       tls:
          insecure: true
          insecure_skip_verify: true
   service:
     pipelines:
       traces:
         receivers: [zipkin]
         exporters: [otlp]